version: '3'

services:
  web:
    build: .
    command: gunicorn memories_app.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - .:/code
    expose:
      - 8000
    env_file:
      - env.dev
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      ./nginx
    depends_on:
      - web
    ports:
      - '80:80'
      - '443:443'
