# Generated by Django 3.2 on 2021-05-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_memory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={},
        ),
    ]
