# Generated by Django 3.2 on 2021-05-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_memory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': 'memories'},
        ),
        migrations.AddField(
            model_name='memory',
            name='pub_date',
            field=models.DateTimeField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
