# Generated by Django 3.2 on 2021-05-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210506_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
